<!DOCTYPE html><html lang="pt-br"><head>
  <meta charset="utf-8">
  <title>MobElementSubscriptions</title>
  <base href="/assinaturas/">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script type="text/javascript" src="/ruxitagentjs_ICA7NVfghjqrux_10313250422105919.js" data-dtconfig="rid=RID_-96628613|rpid=-291020080|domain=santander.com.br|reportUrl=/rb_bf75937itj|app=0cb6a62a52012dc9|cuc=ymexr7ea|ssc=1|owasp=1|mel=100000|featureHash=ICA7NVfghjqrux|doNotDetect=scr|md=mdcc1=abody ^rb app-root ^rb step-start ^rb conversation-step ^rb div ^rb div ^rb form ^rb div ^rb div ^rb input-text-wrapper ^rb input|lastModification=1749135626332|tp=500,50,0|rdnt=1|uxrgce=1|agentUri=/ruxitagentjs_ICA7NVfghjqrux_10313250422105919.js"></script><link rel="icon" type="image/x-icon" href="src/favicon.ico">
<style>*,:after,:before{margin:0;padding:0}body{height:100%;width:100%}@media (min-width:768px){}@media (min-width:768px){}@media (min-width:768px){}:root{--blue:#007bff;--indigo:#6610f2;--purple:#6f42c1;--pink:#e83e8c;--red:#dc3545;--orange:#fd7e14;--yellow:#ffc107;--green:#28a745;--teal:#20c997;--cyan:#17a2b8;--white:#fff;--gray:#6c757d;--gray-dark:#343a40;--primary:#007bff;--secondary:#6c757d;--success:#28a745;--info:#17a2b8;--warning:#ffc107;--danger:#dc3545;--light:#f8f9fa;--dark:#343a40;--breakpoint-xs:0;--breakpoint-sm:576px;--breakpoint-md:768px;--breakpoint-lg:992px;--breakpoint-xl:1200px;--font-family-sans-serif:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,"Helvetica Neue",Arial,"Noto Sans",sans-serif,"Apple Color Emoji","Segoe UI Emoji","Segoe UI Symbol","Noto Color Emoji";--font-family-monospace:SFMono-Regular,Menlo,Monaco,Consolas,"Liberation Mono","Courier New",monospace}*,:after,:before{box-sizing:border-box}html{font-family:sans-serif;line-height:1.15;-webkit-text-size-adjust:100%;-webkit-tap-highlight-color:transparent}body{margin:0;font-family:-apple-system,BlinkMacSystemFont,Segoe UI,Roboto,Helvetica Neue,Arial,Noto Sans,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol,Noto Color Emoji;font-size:1rem;font-weight:400;line-height:1.5;color:#212529;text-align:left;background-color:#fff}@media print{*,:after,:before{text-shadow:none!important;box-shadow:none!important}@page{size:a3}body{min-width:992px!important}}:root{--swiper-theme-color:#007aff}:root{--swiper-navigation-size:44px}</style><link rel="stylesheet" href="styles.css" media="print" onload="this.media='all'"><noscript><link rel="stylesheet" href="styles.css"></noscript></head>
<body>
  <mob-subscriptions></mob-subscriptions>
<script src="polyfills.js" defer></script><script src="main.js" defer></script>

<script type="text/javascript"  src="/bPSwrvJX37BUCkaamMaZVAgucEA/E1pOfwzr9kDQia/XkczNCdR/LEw/jKSdBOzg"></script></body></html>